name: Build binaries

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.device }} - ${{ matrix.esphome }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - rgb-light
          - rgbww-light
          - rgbct-light
          - garage-door
          - ws2812b
          - mini-switch
          - relay-board-x1
          - relay-board-x2
          - relay-board-x4
          - relay-board-x8
          - smart-plug
          - sw01
          - sw02
          - sw03
          - sw04
          - cb20
          - ls-4p-3wire
          - ls-4p-4wire
        esphome:
          - latest
          - beta
          - dev

    container: ghcr.io/esphome/esphome:${{ matrix.esphome }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: ./.github/actions/build
        with:
          device: ${{ matrix.device }}
