name: CI

on:
  pull_request:

jobs:
  build:
    name: Building ${{ matrix.device }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        device:
          - rgb-light
          - rgbww-light
          - rgbct-light
          - garage-door
          - ws2812b
          - mini-switch
          - relay-board-x1
          - relay-board-x2
          - relay-board-x4
          - relay-board-x8
          - smart-plug
          - smart-plug-v2
          - sw01
          - sw01-v2
          - sw02
          - sw02-v2
          - sw03
          - sw04
          - cb02
          - ls-4p-3wire
          - ls-4p-4wire
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: esphome/build-action@v1.1.0
        id: esphome-build
        with:
          yaml_file: athom-${{ matrix.device }}.yaml
